name: CI Pipeline

on:
  pull_request:
    branches:
      - main 
     # Trigger on pull request to `main`

jobs:
  test:
    runs-on: ubuntu-latest  # GitHub-hosted runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt 

        # Linting step (using pylint as an example for Python)
      - name: Run Pylint
        run: |
          pip install pylint
          pylint main.py  # Replace with your actual Python code directory
        continue-on-error: false  # Make sure the pipeline fails if linting fails

      # Testing step (replace with your testing framework, e.g., pytest)
      - name: Run tests
        run: |
          pip install pytest
          pytest --maxfail=1 --disable-warnings -q  # Adjust according to your test suite
        continue-on-error: false  # Ensure the pipeline fails if tests fail

      # Additional steps like formatting check, if required (e.g., black, flake8)
      - name: Check code formatting (optional)
        run: |
          pip install black
          black --main.py  # Replace with the code directory you want to check
        continue-on-error: false  # Ensure the pipeline fails if formatting check fails
          